### ISSUE TITLE
Uncouple from Playservices, use Openstreetmap provider

### ISSUE THREAD

**Issue by KlausHans** [tankste/app#7]
Hello, promising project, nice.

I just tried to use it on LineageOs without installed Playservices. Unfortunately the App does not work without Playservices (no map). It would be really great to uncouple the app from it, e.g. use some Openstreetmapservice.

**Comment by Fabi755** [comment]
Hey Klaus! Thanks for your Feedback!

We get some requests about apple map support (#4). And I have already thinking about multiple systems and basically about the open source idea. I think we should use different map types different platforms & app stores.

I would suggest:

| OS                                   | Store                 | Map Provider        |
| ----------------------- | --------------- | ----------------- |
| Googles Android            |  Play Store        | Google Maps        |
| Other Android Systems |  f-droid.org, ... |  Open Street Map |
| iOS/iPad OS                    | AppStore          | Apple Map            |

Sounds this good for you?

**Comment by KlausHans** [comment]
Sounds perfect to me. :+1: 
Thank you for the quick response.

**Comment by kojid0** [comment]
What advantage comes from integrating 3 different map providers? I don't think Apple Map or Google Maps can offer a lot more than OpenStreetMap...

**Comment by Fabi755** [comment]
It's near to the given OS system and the user have a known environment (UI, gestures). 

I get a lot of mails from iOS user that want to see Apple Maps instead of Google Maps. As an Android Users I prefer Google Maps. And for the open source Android projects without Play Service we need a third solution as well.

With a clean abstract solution we have little bit more work at the initial step. But after all basic things done, there is not a lot of work anymore. It all depends on the architecture :slightly_smiling_face:
